config/routes.rb
Rails.application.routes.draw do
  get 'questions/index'

  get 'user_pairs/new'

  devise_for :users
  resources :users, only: [:index, :show]
  resources :surveys, only: [:new, :edit, :update, :show] do
    resources :survey_questions
  end

  root 'pages#home'

  get  '/help',    to: 'pages#help'
  get  '/about',   to: 'pages#about'

  patch '/surveys/:id/edit',  to: 'surveys#update'
  get '/surveys/:id',  to: 'surveys#show'
  get '/surveys',  to: 'surveys#new'
  post '/surveys', to: 'surveys#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :questions
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  store_accessor :options

  belongs_to :category
  has_many :survey_questions
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_secure_token

  has_one :user_pair, dependent: :destroy
  has_many :users, through: :userpair, class_name: 'UserPair'
  has_many :survey_questions
  
  accepts_nested_attributes_for :user_pair, :survey_questions
end

app/models/survey_question.rb
class SurveyQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :survey, optional: true
  belongs_to :category

  accepts_nested_attributes_for :survey

  attr_accessor :status

  scope :granular, -> (granular) { joins('INNER JOIN questions ON questions.id = survey_questions.question_id').where("parent_id IS NULL") unless granular }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name,  presence: true, length: { maximum: 50 },
    uniqueness: { case_sensitive: false }

  has_many :user_pairs, foreign_key: 'user1_id'
  # has_many :user_pairs, foreign_key: 'user2_id'

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/models/user_pair.rb
class UserPair < ApplicationRecord
  belongs_to :user1, class_name: 'User', optional: true
  belongs_to :user2, class_name: 'User', optional: true
  belongs_to :survey, optional: true

  validates :user1_name, presence: true
  validates :user2_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include Devise::Controllers::Helpers

  def new
    @survey = Survey.new
    @survey.build_user_pair
  end

  def edit
    @survey = Survey.find_by(token: params[:id])

    redirect_to survey_path @survey.token if @survey.taken >= 2

    @categories = @survey.category_ids.map { |c| Category.find(c) }
    @categories.each do |c|
      c.questions.each do |q|
        @survey.survey_questions.build(question_id: q.id, survey_id: @survey.id)
      end
    end
  end

  def update
    @survey = Survey.find_by(token: params[:id])

    survey_params[:survey_questions].keys.each do |id|
      survey_question = @survey.survey_questions.where(id: id).first
      survey_question.value << survey_params[:survey_questions][id][:value]
      survey_question.save
    end

    @survey.taken += 1

    if user_signed_in?
      @survey.user_pair.user1_id = current_user.id if @survey.taken == 1
      @survey.user_pair.user2_id = current_user.id if @survey.taken > 1
    end

    if @survey.save
      email = @survey.user_pair.user2_email
      if @survey.taken == 1 && !@survey.user_pair.user2_email.blank?
        SurveyMailer.survey_email(email, @survey.token).deliver
      else
        SurveyMailer.survey_completed_email(@survey.user_pair.user1_email,
          @survey.token).deliver unless @survey.user_pair.user1_email.blank?
        SurveyMailer.survey_completed_email(@survey.user_pair.user2_email,
          @survey.token).deliver unless @survey.user_pair.user2_email.blank?
      end

      flash[:success] = "Successfully submitted survey!"
      redirect_to survey_path @survey.token
    else
      render 'edit'
    end
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.category_ids.delete_at(0)

    @categories = @survey.category_ids.map { |c| Category.find(c) }
    @categories.each do |c|
      c.questions.each do |q|
        if (q.parent_id && @survey.granular) || !q.parent_id
          @survey.survey_questions.build(question_id: q.id, survey_id: @survey.id,
                                         category_id: c.id)
        end
      end
    end

    if @survey.save
      flash[:success] = "Survey submitted"
      redirect_to edit_survey_path @survey.token
    else
      render 'new'
    end
  end

  def show
    @survey = Survey.find_by(token: params[:id])
    @survey.category_ids.delete('1')
    @categories = @survey.category_ids.map { |c| Category.find(c) }
  end

  def info
  end

  def destroy
    survey = Survey.find_by(token: params[:id])
    Survey.delete(survey.id)
  end

  private

  def survey_params
    params.require(:survey).permit(:granular, category_ids: [],
           user_pair_attributes: [:user1_name, :user1_genitals, :user1_email, :user2_name, :user2_genitals, :user2_email],
           survey_questions: [:value, :status])
  end
end

app/controllers/user_pairs_controller.rb
class UserPairsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @pairs = UserPair.where('user1_id = ? OR user2_id = ?', @user.id, @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns full title on a per-page basis.
  def full_title(page_title = '')
    base_title = 'Sex+'
    if page_title.empty?
      base_title
    else
      base_title + ' | ' + page_title
    end
  end

  def nav_link(text, path)
    active = current_page?(path) ? 'is-active' : ''
    link_to text, path, class: 'mdl-layout__tab ' + active
  end

  def replace_tokens(description, name1, name2)
    desc = description.gsub(/\$1/, name1)
    desc.gsub!(/\$2/, name2)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
  def fantasy_rating(rating)
    if rating >= 6
      'Interested'
    elsif rating >= 1
      'If partner is interested'
    end
  end

  def fantasy_stars(rating)
    rating = rating > 5 ? rating - 5 : rating
    ('<i class="material-icons fantasy-rating">favorite</i>' * rating).html_safe
  end

  def preference_rating(rating, preference)
    rating = rating.to_i

    if rating == 0
      preference.question.options[0]
    else
      ndx = (rating / 5).floor
      preference.question.options[ndx]
    end
  end

  def preference_stars(rating)
    rating = rating.to_i
    stars = rating % 5 > 0 ? rating % 5 : 1

    ('<i class="material-icons fantasy-rating">favorite</i>' * stars).html_safe
  end

  def parse_token(message, user1, user2)
    msg = message.gsub(/\$1/, user1)
    msg.gsub(/\$2/, user2)
  end
end

app/helpers/user_pairs_helper.rb
module UserPairsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/shim' %>
  </head>

  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">

    <div class="mdl-layout mdl-js-layout mdl-layout--no-desktop-drawer-button mdl-layout--fixed-header">
      <%= render 'shared/nav/nav' %>
      <main class="mdl-layout__content">
        <%= yield %>
      </main>

      <%= debug(params) if Rails.env.development? %>
    </div>

    <!-- <%= render 'shared/footer' %> -->
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
About

app/views/pages/help.html.erb
<% provide(:title, 'Help') %>
Help

app/views/pages/home.html.erb
<div class="mdl-layout__jumbo mdl-layout__index mdl-color--primary">
    <div class="mdl-layout__header-row"></div>
    <div class="mdl-layout__header-row">
        <h1>Sex+</h1>
    </div>
    <div class="mdl-layout__header-row">
        Redefining healthy communication. Tagline here.
    </div>
    <% unless user_signed_in? %>
      <div class="mdl-layout__header-row">
          <div class="mdl-layout-spacer"></div>
          <%= link_to "Sign up now", new_user_registration_path,
              class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
          <div class="mdl-layout-spacer"></div>
      </div>
    <% end %>
    <div class="mdl-layout__header-row"></div>
</div>

<section class="section--center mdl-grid">

    <%= render 'shared/flash' %>

    <div class="mdl-card mdl-card--fixed-height-title mdl-card--fixed-height-text
                mdl-cell mdl-cell--4-col-desktop mdl-cell--8-col-tablet mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--survey">
            <h2 class="mdl-card__title-text">Survey</h2>
        </div>
        <div class="mdl-card__supporting-text">
            Discover and share sexual interests with your partner! Customize the survey to be as kinky or as granular as you want.
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <%= link_to 'Take Survey', new_survey_path, class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
        </div>
    </div>
    <div class="mdl-card mdl-card--fixed-height-title mdl-card--fixed-height-text mdl-cell mdl-cell--4-col  mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--compendium">
            <h2 class="mdl-card__title-text">Compendium</h2>
        </div>
        <div class="mdl-card__supporting-text">
            Learn about new sex acts, kinks, and jargon in an easy-to-search database.
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                View Compendium
            </a>
        </div>
    </div>
    <div class="mdl-card mdl-card--fixed-height-title mdl-card--fixed-height-text mdl-cell mdl-cell--4-col  mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--articles">
            <h2 class="mdl-card__title-text">Articles</h2>
        </div>
        <div class="mdl-card__supporting-text">
            Read articles on a variety of topics, including effective communication, kink safety guidelines, and sex myths.
        </div>
        <div class="mdl-card__actions mdl-card--border">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                View Updates
            </a>
        </div>
    </div>
</section>

app/views/questions/index.html.erb
<% provide(:title, 'Questions') %>

<div class="mdl-layout__jumbo mdl-layout__index mdl-color--primary">
    <div class="mdl-layout__header-row"></div>
    <div class="mdl-layout__header-row">
        <h1>Sex+ Survey Questions</h1>
    </div>
    <div class="mdl-layout__header-row">
        All of the categories and their questions!
    </div>
    <div class="mdl-layout__header-row"></div>
</div>

<section class="section--center mdl-grid">
  <% @categories.each do |category| %>
    <div class="mdl-card mdl-card--fixed-height-title mdl-cell mdl-cell--12-col mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--survey">
            <h2 class="mdl-card__title-text">
              <%= category.name %>
            </h2>
            <h3 class="mdl-card__title-subtext"><%= category.description %></h3>
        </div>
        <div class="mdl-card__supporting-text">
          <% category.questions.each do |question| %>
            <% if question.description.include? '$' %>
              <%= replace_tokens question.description, "Georgia O'keeffe", "Virginia Wolf" %>
              <br /><%= replace_tokens question.description, "Virginia Wolf", "Georgia O'keeffe" %>
            <% else %>
              <%= question.description %>
            <% end %>

            <!-- Display select options -->
            <% unless question.options.nil? %>
              <select>
                <% question.options.each do |key, value| %>
                  <option><%= value %></option>
                <% end %>
              </select>
            <% end %>
            <br /><br />
          <% end %>
        </div>
    </div>
  <% end %>
</section>

app/views/shared/nav/_left-items.html.erb
<%= nav_link "Home", '/' %>
<%= nav_link "Survey", new_survey_path %>
<%= nav_link "Resources", 'resources' %>
<%= nav_link "Articles", 'articles' %>
<%= nav_link "About", about_path %>

app/views/shared/nav/_right-items.html.erb
<% if user_signed_in? %>
  <%= nav_link current_user.name, user_path(current_user) %>
  <%= nav_link "Settings", edit_user_registration_path %>
  <%= link_to "Logout", destroy_user_session_path, :method => :delete, class: "mdl-layout__tab" %>
<% else %>
  <%= nav_link "Log In", new_user_session_path %>
  <%= nav_link "Register", new_user_registration_path %>
<% end %>

app/views/surveys/new.html.erb
<% provide(:title, 'Pre-Survey') %>
<div class="mdl-layout__jumbo mdl-layout__survey mdl-color--primary">
    <div class="mdl-layout__header-row"></div>
    <div class="mdl-layout__header-row">
        <h1>Sex+ Survey</h1>
    </div>
    <div class="mdl-layout__header-row">
        Discover and share sexual interests with your partner! Customize the survey to be as kinky or as granular as you want. But first, let us know some information so we can personalize your survey!
    </div>
    <div class="mdl-layout__header-row"></div>
</div>

<%= form_for @survey do |form| %>

  <%= form.fields_for :user_pair do |pair| %>
    <section class="section--center mdl-grid">

      <% @survey.errors.full_messages.each do |message| %>
        <div class="mdl-card mdl-card--flash mdl-cell mdl-cell--12-col-desktop
                    mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--survey">
                <h2 class="mdl-card__title-text">
                  <%= message %>
                </h2>
            </div>
        </div>
      <% end %>

        <div class="mdl-card mdl-card--fixed-height-title mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--yours">
                <h2 class="mdl-card__title-text">You</h2>
            </div>
            <div class="mdl-card__supporting-text">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--card">
                    <%= pair.text_field :user1_name, class: 'mdl-textfield__input',
                        value: user_signed_in? ? current_user.name.capitalize : '' %>
                    <label class="mdl-textfield__label" for="survey_user_pair_attributes_user1_name">Georgia O'keefe</label>
                </div>
                <br />
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--card">
                    <%= pair.email_field :user1_email, class: 'mdl-textfield__input',
                        value: user_signed_in? ? current_user.email : '' %>
                    <label class="mdl-textfield__label" for="survey_user_pair_attributes_user1_email">georgiaokeefe@example.com</label>
                </div>
                <br/>I have a...
                  <div class="mdl-card__form">
                      <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="survey_user_pair_attributes_user1_genitals_penis">
                          <%= pair.radio_button :user1_genitals, 'penis', class: "mdl-radio__button" %>
                          <span class="mdl-radio__label">Penis</span>
                      </label>
                      <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="survey_user_pair_attributes_user1_genitals_vagina">
                          <%= pair.radio_button :user1_genitals, 'vagina', class: "mdl-radio__button" %>
                          <span class="mdl-radio__label">Vagina</span>
                      </label>
                      <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="survey_user_pair_attributes_user1_genitals_other">
                          <%= pair.radio_button :user1_genitals, 'other', class: "mdl-radio__button" %>
                          <span class="mdl-radio__label">Other</span>
                      </label>
                  </div>
            </div>
        </div>

        <div class="mdl-card mdl-card--fixed-height-title mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--theirs">
                <h2 class="mdl-card__title-text">Them</h2>
            </div>
            <div class="mdl-card__supporting-text">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--card">
                    <%= pair.text_field :user2_name, class: 'mdl-textfield__input' %>
                    <label class="mdl-textfield__label" for="survey_user_pair_attributes_user2_name">Virginia Wolf</label>
                </div>
                <br />
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--card">
                    <%= pair.email_field :user2_email, class: 'mdl-textfield__input' %>
                    <label class="mdl-textfield__label" for="survey_user_pair_attributes_user2_email">virginiawolf@example.com</label>
                </div>
                <br/>They have a...
                <div class="mdl-card__form">
                    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="survey_user_pair_attributes_user2_genitals_penis">
                        <%= pair.radio_button :user2_genitals, 'penis', class: "mdl-radio__button" %>
                        <span class="mdl-radio__label">Penis</span>
                    </label>
                    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="survey_user_pair_attributes_user2_genitals_vagina">
                        <%= pair.radio_button :user2_genitals, 'vagina', class: "mdl-radio__button" %>
                        <span class="mdl-radio__label">Vagina</span>
                    </label>
                    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="survey_user_pair_attributes_user2_genitals_other">
                        <%= pair.radio_button :user2_genitals, 'other', class: "mdl-radio__button" %>
                        <span class="mdl-radio__label">Other</span>
                    </label>
                </div>
            </div>
        </div>

        <div class="mdl-card mdl-cell mdl-card--fixed-height-title mdl-cell--12-col  mdl-shadow--2dp">
            <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--categories">
                <h2 class="mdl-card__title-text">Categories</h2>
            </div>
            <div class="mdl-card__supporting-text">
                Select which categories you would like to be included in your survey. For a full list of questions, see
                <%= link_to 'here', questions_index_path %>.
                <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |category| %>
                  <%= category.label class: 'mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect' do %>
                    <%= category.check_box class: 'mdl-checkbox__input' %>
                    <span class="mdl-checkbox__label">
                      <%= category.text %>
                    </span>
                    <span class="mdl-checkbox__description">
                      <%= category.object.description %>
                    </span>
                  <% end %>
                <% end %>
                <%= form.label :granular, class: 'mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect' do %>
                  <%= form.check_box :granular, value: true, class: 'mdl-checkbox__input' %>
                  <span class="mdl-checkbox__label">
                    Granular
                  </span>
                  <span class="mdl-checkbox__description">
                    Break large items down into multiple sub-items, e.g. "spoon" will become "be the little spoon" and "be the big spoon"
                  </span>
                <% end %>
            </div>
            <div class="mdl-layout-spacer"></div>
        </div>

        <div class="mdl-grid">
            <div class="mdl-layout-spacer"></div>
            <%= form.submit 'Start Survey',
                class: "mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" %>
            <div class="mdl-layout-spacer"></div>
        </div>

    </section>
  <% end %>
<% end %>

app/views/surveys/show.html.erb
<% provide(:title, 'Survey Results') %>
<div class="mdl-layout__jumbo mdl-layout__survey mdl-color--primary">
    <div class="mdl-layout__header-row"></div>
    <div class="mdl-layout__header-row">
        <h1>Sex+ Survey Results</h1>
    </div>
    <div class="mdl-layout__header-row">
        See how you and your partners' answers line up! Remember that fantasies that one of you answered "no" to will not show up.
    </div>
    <div class="mdl-layout__header-row"></div>
</div>

<section class="section--center mdl-grid">
  <% if @survey.taken < 2 %>
    <div class="mdl-card mdl-card--flash mdl-cell mdl-cell--12-col-desktop
                mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--survey">
            <h2 class="mdl-card__title-text">
              <%= @survey.user_pair.user2_name %> hasn't taken the survey!
            </h2>
        </div>
        <div class="mdl-card__supporting-text">
          Direct them to <%= link_to edit_survey_url, edit_survey_path %>.
        </div>
    </div>

  <% else %>

    <div class="mdl-card mdl-card--fixed-height-title mdl-cell mdl-cell--6-col-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--yours">
        <h2 class="mdl-card__title-text">
          <%= @survey.user_pair.user1_name %>
        </h2>
      </div>
      <div class="mdl-card__supporting-text">
        <div class="mdl-grid">
          <% @survey.survey_questions.where(category_id: 1).each do |preference| %>
            <% if preference.value[0] %>
              <div class="mdl-cell mdl-cell--9-col-desktop mdl-cell--8-col-tablet">
                <%= preference.question.description %>
                <span class='preference'><%= preference_rating preference.value[0], preference %></span>
              </div>
              <div class="mdl-cell mdl-cell--3-col-desktop mdl-cell--8-col-tablet">
                <%= preference_stars preference.value[0] %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="mdl-card mdl-card--fixed-height-title mdl-cell mdl-cell--6-col-desktop mdl-cell--4-col-tablet mdl-cell--4-col-phone mdl-shadow--2dp">
      <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--theirs">
        <h2 class="mdl-card__title-text">
          <%= @survey.user_pair.user2_name %>
        </h2>
      </div>
      <div class="mdl-card__supporting-text">
        <div class="mdl-grid">
          <% @survey.survey_questions.where(category_id: 1).each do |preference| %>
            <% if preference.value[1] %>
              <div class="mdl-cell mdl-cell--9-col-desktop mdl-cell--8-col-tablet">
                <%= preference.question.description %>
                <span class='preference'><%= preference_rating preference.value[1], preference %></span>
              </div>
              <div class="mdl-cell mdl-cell--3-col-desktop mdl-cell--8-col-tablet">
                <%= preference_stars preference.value[1] %>
              </div>
            <% else %>
              <div class="mdl-cell"></div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </section>

  <section class="section--center mdl-grid">
    <% @categories.each do |category| %>
      <div class="mdl-card mdl-card--fixed-height-title mdl-cell mdl-cell--12-col mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand mdl-card__title--image mdl-card__title--yours">
          <h2 class="mdl-card__title-text">
            <%= category.name %>
          </h2>
          <h3 class="mdl-card__title-subtext"><%= category.description %></h3>
        </div>
        <div class="mdl-card__supporting-text">
          <div class="mdl-grid">
            <% survey_questions = @survey.survey_questions.where(category_id: category.id).where("array_length(value, 1) > 1").where.not("'0' = ANY (value)").order(:id) %>

            <% if survey_questions.count == 0 %>
              Whoops! There are no mutual wants for this category.
            <% else %>
              <div class="mdl-cell mdl-cell--6-col mdl-cell--hide-phone">
              </div>
              <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--hide-phone fantasy__name">
                <%= @survey.user_pair.user1_name %>'s response
              </div>
              <div class="mdl-cell mdl-cell--3-col mdl-cell--4-col-tablet mdl-cell--hide-phone fantasy__name">
                <%= @survey.user_pair.user2_name %>'s response
              </div>

              <% survey_questions.each do |question| %>
                <div class="mdl-cell mdl-cell--6-col fantasy__label">
                  <% if question.question.description.include? '$' %>
                    <%= parse_token question.question.description, @survey.user_pair.user1_name, @survey.user_pair.user2_name %>
                  <% else %>
                    <%= question.question.description %>
                  <% end %>
                </div>
                <div class="mdl-cell mdl-cell--3-col mdl-cell--2-col-phone mdl-cell--4-col-tablet">
                  <span class="mdl-cell--hide-desktop mdl-cell--hide-tablet fantasy__name">
                    <%= @survey.user_pair.user1_name %>'s response <br/>
                  </span>
                  <%= fantasy_rating question.value[0].to_i %>
                  <span class="mdl-cell--hide-phone"><br/><%= fantasy_stars question.value[0].to_i %></span>
                </div>
                <div class="mdl-cell mdl-cell--3-col mdl-cell--2-col-phone mdl-cell--4-col-tablet">
                  <span class="mdl-cell--hide-desktop mdl-cell--hide-tablet fantasy__name">
                    <%= @survey.user_pair.user2_name %>'s response <br/>
                  </span>
                  <%= fantasy_rating question.value[1].to_i %>
                  <span class="mdl-cell--hide-phone"><br/><%= fantasy_stars question.value[1].to_i %></span>
                </div>
                <div class="mdl-cell mdl-cell--hide-desktop mdl-cell--hide-tablet mdl-cell--2-col-phone">
                  <%= fantasy_stars question.value[0].to_i %>
                </div>
                <div class="mdl-cell mdl-cell--hide-desktop mdl-cell--hide-tablet mdl-cell--2-col-phone">
                  <%= fantasy_stars question.value[1].to_i %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</section>